// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adjacency_list.proto

#ifndef PROTOBUF_adjacency_5flist_2eproto__INCLUDED
#define PROTOBUF_adjacency_5flist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace range {
namespace db {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_adjacency_5flist_2eproto();
void protobuf_AssignDesc_adjacency_5flist_2eproto();
void protobuf_ShutdownFile_adjacency_5flist_2eproto();

class AdjacencyLists;
class AdjacencyLists_Adjacency;
class AdjacencyLists_Edges;
class AdjacencyLists_GraphVersions;

// ===================================================================

class AdjacencyLists_Adjacency : public ::google::protobuf::Message {
 public:
  AdjacencyLists_Adjacency();
  virtual ~AdjacencyLists_Adjacency();

  AdjacencyLists_Adjacency(const AdjacencyLists_Adjacency& from);

  inline AdjacencyLists_Adjacency& operator=(const AdjacencyLists_Adjacency& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdjacencyLists_Adjacency& default_instance();

  void Swap(AdjacencyLists_Adjacency* other);

  // implements Message ----------------------------------------------

  AdjacencyLists_Adjacency* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdjacencyLists_Adjacency& from);
  void MergeFrom(const AdjacencyLists_Adjacency& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int64 version() const;
  inline void set_version(::google::protobuf::int64 value);

  // required string id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  inline ::std::string* release_id();
  inline void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:range.db.AdjacencyLists.Adjacency)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 version_;
  ::std::string* id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_adjacency_5flist_2eproto();
  friend void protobuf_AssignDesc_adjacency_5flist_2eproto();
  friend void protobuf_ShutdownFile_adjacency_5flist_2eproto();

  void InitAsDefaultInstance();
  static AdjacencyLists_Adjacency* default_instance_;
};
// -------------------------------------------------------------------

class AdjacencyLists_Edges : public ::google::protobuf::Message {
 public:
  AdjacencyLists_Edges();
  virtual ~AdjacencyLists_Edges();

  AdjacencyLists_Edges(const AdjacencyLists_Edges& from);

  inline AdjacencyLists_Edges& operator=(const AdjacencyLists_Edges& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdjacencyLists_Edges& default_instance();

  void Swap(AdjacencyLists_Edges* other);

  // implements Message ----------------------------------------------

  AdjacencyLists_Edges* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdjacencyLists_Edges& from);
  void MergeFrom(const AdjacencyLists_Edges& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .range.db.AdjacencyLists.Adjacency edges = 1;
  inline int edges_size() const;
  inline void clear_edges();
  static const int kEdgesFieldNumber = 1;
  inline const ::range::db::AdjacencyLists_Adjacency& edges(int index) const;
  inline ::range::db::AdjacencyLists_Adjacency* mutable_edges(int index);
  inline ::range::db::AdjacencyLists_Adjacency* add_edges();
  inline const ::google::protobuf::RepeatedPtrField< ::range::db::AdjacencyLists_Adjacency >&
      edges() const;
  inline ::google::protobuf::RepeatedPtrField< ::range::db::AdjacencyLists_Adjacency >*
      mutable_edges();

  // @@protoc_insertion_point(class_scope:range.db.AdjacencyLists.Edges)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::range::db::AdjacencyLists_Adjacency > edges_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_adjacency_5flist_2eproto();
  friend void protobuf_AssignDesc_adjacency_5flist_2eproto();
  friend void protobuf_ShutdownFile_adjacency_5flist_2eproto();

  void InitAsDefaultInstance();
  static AdjacencyLists_Edges* default_instance_;
};
// -------------------------------------------------------------------

class AdjacencyLists_GraphVersions : public ::google::protobuf::Message {
 public:
  AdjacencyLists_GraphVersions();
  virtual ~AdjacencyLists_GraphVersions();

  AdjacencyLists_GraphVersions(const AdjacencyLists_GraphVersions& from);

  inline AdjacencyLists_GraphVersions& operator=(const AdjacencyLists_GraphVersions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdjacencyLists_GraphVersions& default_instance();

  void Swap(AdjacencyLists_GraphVersions* other);

  // implements Message ----------------------------------------------

  AdjacencyLists_GraphVersions* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdjacencyLists_GraphVersions& from);
  void MergeFrom(const AdjacencyLists_GraphVersions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 version = 1;
  inline int version_size() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int64 version(int index) const;
  inline void set_version(int index, ::google::protobuf::int64 value);
  inline void add_version(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      version() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_version();

  // @@protoc_insertion_point(class_scope:range.db.AdjacencyLists.GraphVersions)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > version_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_adjacency_5flist_2eproto();
  friend void protobuf_AssignDesc_adjacency_5flist_2eproto();
  friend void protobuf_ShutdownFile_adjacency_5flist_2eproto();

  void InitAsDefaultInstance();
  static AdjacencyLists_GraphVersions* default_instance_;
};
// -------------------------------------------------------------------

class AdjacencyLists : public ::google::protobuf::Message {
 public:
  AdjacencyLists();
  virtual ~AdjacencyLists();

  AdjacencyLists(const AdjacencyLists& from);

  inline AdjacencyLists& operator=(const AdjacencyLists& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdjacencyLists& default_instance();

  void Swap(AdjacencyLists* other);

  // implements Message ----------------------------------------------

  AdjacencyLists* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdjacencyLists& from);
  void MergeFrom(const AdjacencyLists& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef AdjacencyLists_Adjacency Adjacency;
  typedef AdjacencyLists_Edges Edges;
  typedef AdjacencyLists_GraphVersions GraphVersions;

  // accessors -------------------------------------------------------

  // required int64 list_version = 1;
  inline bool has_list_version() const;
  inline void clear_list_version();
  static const int kListVersionFieldNumber = 1;
  inline ::google::protobuf::int64 list_version() const;
  inline void set_list_version(::google::protobuf::int64 value);

  // required int32 crc32 = 2;
  inline bool has_crc32() const;
  inline void clear_crc32();
  static const int kCrc32FieldNumber = 2;
  inline ::google::protobuf::int32 crc32() const;
  inline void set_crc32(::google::protobuf::int32 value);

  // required .range.db.AdjacencyLists.Edges forward = 3;
  inline bool has_forward() const;
  inline void clear_forward();
  static const int kForwardFieldNumber = 3;
  inline const ::range::db::AdjacencyLists_Edges& forward() const;
  inline ::range::db::AdjacencyLists_Edges* mutable_forward();
  inline ::range::db::AdjacencyLists_Edges* release_forward();
  inline void set_allocated_forward(::range::db::AdjacencyLists_Edges* forward);

  // required .range.db.AdjacencyLists.Edges reverse = 4;
  inline bool has_reverse() const;
  inline void clear_reverse();
  static const int kReverseFieldNumber = 4;
  inline const ::range::db::AdjacencyLists_Edges& reverse() const;
  inline ::range::db::AdjacencyLists_Edges* mutable_reverse();
  inline ::range::db::AdjacencyLists_Edges* release_reverse();
  inline void set_allocated_reverse(::range::db::AdjacencyLists_Edges* reverse);

  // @@protoc_insertion_point(class_scope:range.db.AdjacencyLists)
 private:
  inline void set_has_list_version();
  inline void clear_has_list_version();
  inline void set_has_crc32();
  inline void clear_has_crc32();
  inline void set_has_forward();
  inline void clear_has_forward();
  inline void set_has_reverse();
  inline void clear_has_reverse();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 list_version_;
  ::range::db::AdjacencyLists_Edges* forward_;
  ::range::db::AdjacencyLists_Edges* reverse_;
  ::google::protobuf::int32 crc32_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_adjacency_5flist_2eproto();
  friend void protobuf_AssignDesc_adjacency_5flist_2eproto();
  friend void protobuf_ShutdownFile_adjacency_5flist_2eproto();

  void InitAsDefaultInstance();
  static AdjacencyLists* default_instance_;
};
// ===================================================================


// ===================================================================

// AdjacencyLists_Adjacency

// required int64 version = 1;
inline bool AdjacencyLists_Adjacency::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AdjacencyLists_Adjacency::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AdjacencyLists_Adjacency::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AdjacencyLists_Adjacency::clear_version() {
  version_ = GOOGLE_LONGLONG(0);
  clear_has_version();
}
inline ::google::protobuf::int64 AdjacencyLists_Adjacency::version() const {
  return version_;
}
inline void AdjacencyLists_Adjacency::set_version(::google::protobuf::int64 value) {
  set_has_version();
  version_ = value;
}

// required string id = 2;
inline bool AdjacencyLists_Adjacency::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AdjacencyLists_Adjacency::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AdjacencyLists_Adjacency::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AdjacencyLists_Adjacency::clear_id() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    id_->clear();
  }
  clear_has_id();
}
inline const ::std::string& AdjacencyLists_Adjacency::id() const {
  return *id_;
}
inline void AdjacencyLists_Adjacency::set_id(const ::std::string& value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void AdjacencyLists_Adjacency::set_id(const char* value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void AdjacencyLists_Adjacency::set_id(const char* value, size_t size) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AdjacencyLists_Adjacency::mutable_id() {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  return id_;
}
inline ::std::string* AdjacencyLists_Adjacency::release_id() {
  clear_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = id_;
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AdjacencyLists_Adjacency::set_allocated_id(::std::string* id) {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    delete id_;
  }
  if (id) {
    set_has_id();
    id_ = id;
  } else {
    clear_has_id();
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// AdjacencyLists_Edges

// repeated .range.db.AdjacencyLists.Adjacency edges = 1;
inline int AdjacencyLists_Edges::edges_size() const {
  return edges_.size();
}
inline void AdjacencyLists_Edges::clear_edges() {
  edges_.Clear();
}
inline const ::range::db::AdjacencyLists_Adjacency& AdjacencyLists_Edges::edges(int index) const {
  return edges_.Get(index);
}
inline ::range::db::AdjacencyLists_Adjacency* AdjacencyLists_Edges::mutable_edges(int index) {
  return edges_.Mutable(index);
}
inline ::range::db::AdjacencyLists_Adjacency* AdjacencyLists_Edges::add_edges() {
  return edges_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::range::db::AdjacencyLists_Adjacency >&
AdjacencyLists_Edges::edges() const {
  return edges_;
}
inline ::google::protobuf::RepeatedPtrField< ::range::db::AdjacencyLists_Adjacency >*
AdjacencyLists_Edges::mutable_edges() {
  return &edges_;
}

// -------------------------------------------------------------------

// AdjacencyLists_GraphVersions

// repeated int64 version = 1;
inline int AdjacencyLists_GraphVersions::version_size() const {
  return version_.size();
}
inline void AdjacencyLists_GraphVersions::clear_version() {
  version_.Clear();
}
inline ::google::protobuf::int64 AdjacencyLists_GraphVersions::version(int index) const {
  return version_.Get(index);
}
inline void AdjacencyLists_GraphVersions::set_version(int index, ::google::protobuf::int64 value) {
  version_.Set(index, value);
}
inline void AdjacencyLists_GraphVersions::add_version(::google::protobuf::int64 value) {
  version_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
AdjacencyLists_GraphVersions::version() const {
  return version_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
AdjacencyLists_GraphVersions::mutable_version() {
  return &version_;
}

// -------------------------------------------------------------------

// AdjacencyLists

// required int64 list_version = 1;
inline bool AdjacencyLists::has_list_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AdjacencyLists::set_has_list_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AdjacencyLists::clear_has_list_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AdjacencyLists::clear_list_version() {
  list_version_ = GOOGLE_LONGLONG(0);
  clear_has_list_version();
}
inline ::google::protobuf::int64 AdjacencyLists::list_version() const {
  return list_version_;
}
inline void AdjacencyLists::set_list_version(::google::protobuf::int64 value) {
  set_has_list_version();
  list_version_ = value;
}

// required int32 crc32 = 2;
inline bool AdjacencyLists::has_crc32() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AdjacencyLists::set_has_crc32() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AdjacencyLists::clear_has_crc32() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AdjacencyLists::clear_crc32() {
  crc32_ = 0;
  clear_has_crc32();
}
inline ::google::protobuf::int32 AdjacencyLists::crc32() const {
  return crc32_;
}
inline void AdjacencyLists::set_crc32(::google::protobuf::int32 value) {
  set_has_crc32();
  crc32_ = value;
}

// required .range.db.AdjacencyLists.Edges forward = 3;
inline bool AdjacencyLists::has_forward() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AdjacencyLists::set_has_forward() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AdjacencyLists::clear_has_forward() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AdjacencyLists::clear_forward() {
  if (forward_ != NULL) forward_->::range::db::AdjacencyLists_Edges::Clear();
  clear_has_forward();
}
inline const ::range::db::AdjacencyLists_Edges& AdjacencyLists::forward() const {
  return forward_ != NULL ? *forward_ : *default_instance_->forward_;
}
inline ::range::db::AdjacencyLists_Edges* AdjacencyLists::mutable_forward() {
  set_has_forward();
  if (forward_ == NULL) forward_ = new ::range::db::AdjacencyLists_Edges;
  return forward_;
}
inline ::range::db::AdjacencyLists_Edges* AdjacencyLists::release_forward() {
  clear_has_forward();
  ::range::db::AdjacencyLists_Edges* temp = forward_;
  forward_ = NULL;
  return temp;
}
inline void AdjacencyLists::set_allocated_forward(::range::db::AdjacencyLists_Edges* forward) {
  delete forward_;
  forward_ = forward;
  if (forward) {
    set_has_forward();
  } else {
    clear_has_forward();
  }
}

// required .range.db.AdjacencyLists.Edges reverse = 4;
inline bool AdjacencyLists::has_reverse() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AdjacencyLists::set_has_reverse() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AdjacencyLists::clear_has_reverse() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AdjacencyLists::clear_reverse() {
  if (reverse_ != NULL) reverse_->::range::db::AdjacencyLists_Edges::Clear();
  clear_has_reverse();
}
inline const ::range::db::AdjacencyLists_Edges& AdjacencyLists::reverse() const {
  return reverse_ != NULL ? *reverse_ : *default_instance_->reverse_;
}
inline ::range::db::AdjacencyLists_Edges* AdjacencyLists::mutable_reverse() {
  set_has_reverse();
  if (reverse_ == NULL) reverse_ = new ::range::db::AdjacencyLists_Edges;
  return reverse_;
}
inline ::range::db::AdjacencyLists_Edges* AdjacencyLists::release_reverse() {
  clear_has_reverse();
  ::range::db::AdjacencyLists_Edges* temp = reverse_;
  reverse_ = NULL;
  return temp;
}
inline void AdjacencyLists::set_allocated_reverse(::range::db::AdjacencyLists_Edges* reverse) {
  delete reverse_;
  reverse_ = reverse;
  if (reverse) {
    set_has_reverse();
  } else {
    clear_has_reverse();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace range

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_adjacency_5flist_2eproto__INCLUDED
