// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adjacency_list.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "adjacency_list.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace range {
namespace db {

namespace {

const ::google::protobuf::Descriptor* AdjacencyLists_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AdjacencyLists_reflection_ = NULL;
const ::google::protobuf::Descriptor* AdjacencyLists_Adjacency_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AdjacencyLists_Adjacency_reflection_ = NULL;
const ::google::protobuf::Descriptor* AdjacencyLists_Edges_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AdjacencyLists_Edges_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_adjacency_5flist_2eproto() {
  protobuf_AddDesc_adjacency_5flist_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "adjacency_list.proto");
  GOOGLE_CHECK(file != NULL);
  AdjacencyLists_descriptor_ = file->message_type(0);
  static const int AdjacencyLists_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists, forwardedges_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists, reverseedges_),
  };
  AdjacencyLists_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AdjacencyLists_descriptor_,
      AdjacencyLists::default_instance_,
      AdjacencyLists_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AdjacencyLists));
  AdjacencyLists_Adjacency_descriptor_ = AdjacencyLists_descriptor_->nested_type(0);
  static const int AdjacencyLists_Adjacency_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists_Adjacency, id_),
  };
  AdjacencyLists_Adjacency_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AdjacencyLists_Adjacency_descriptor_,
      AdjacencyLists_Adjacency::default_instance_,
      AdjacencyLists_Adjacency_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists_Adjacency, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists_Adjacency, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AdjacencyLists_Adjacency));
  AdjacencyLists_Edges_descriptor_ = AdjacencyLists_descriptor_->nested_type(1);
  static const int AdjacencyLists_Edges_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists_Edges, edges_),
  };
  AdjacencyLists_Edges_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AdjacencyLists_Edges_descriptor_,
      AdjacencyLists_Edges::default_instance_,
      AdjacencyLists_Edges_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists_Edges, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdjacencyLists_Edges, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AdjacencyLists_Edges));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_adjacency_5flist_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AdjacencyLists_descriptor_, &AdjacencyLists::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AdjacencyLists_Adjacency_descriptor_, &AdjacencyLists_Adjacency::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AdjacencyLists_Edges_descriptor_, &AdjacencyLists_Edges::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_adjacency_5flist_2eproto() {
  delete AdjacencyLists::default_instance_;
  delete AdjacencyLists_reflection_;
  delete AdjacencyLists_Adjacency::default_instance_;
  delete AdjacencyLists_Adjacency_reflection_;
  delete AdjacencyLists_Edges::default_instance_;
  delete AdjacencyLists_Edges_reflection_;
}

void protobuf_AddDesc_adjacency_5flist_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024adjacency_list.proto\022\010range.db\"\321\001\n\016Adj"
    "acencyLists\0224\n\014forwardEdges\030\001 \002(\0132\036.rang"
    "e.db.AdjacencyLists.Edges\0224\n\014reverseEdge"
    "s\030\002 \002(\0132\036.range.db.AdjacencyLists.Edges\032"
    "\027\n\tAdjacency\022\n\n\002id\030\001 \002(\t\032:\n\005Edges\0221\n\005edg"
    "es\030\001 \003(\0132\".range.db.AdjacencyLists.Adjac"
    "ency", 244);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "adjacency_list.proto", &protobuf_RegisterTypes);
  AdjacencyLists::default_instance_ = new AdjacencyLists();
  AdjacencyLists_Adjacency::default_instance_ = new AdjacencyLists_Adjacency();
  AdjacencyLists_Edges::default_instance_ = new AdjacencyLists_Edges();
  AdjacencyLists::default_instance_->InitAsDefaultInstance();
  AdjacencyLists_Adjacency::default_instance_->InitAsDefaultInstance();
  AdjacencyLists_Edges::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_adjacency_5flist_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_adjacency_5flist_2eproto {
  StaticDescriptorInitializer_adjacency_5flist_2eproto() {
    protobuf_AddDesc_adjacency_5flist_2eproto();
  }
} static_descriptor_initializer_adjacency_5flist_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AdjacencyLists_Adjacency::kIdFieldNumber;
#endif  // !_MSC_VER

AdjacencyLists_Adjacency::AdjacencyLists_Adjacency()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AdjacencyLists_Adjacency::InitAsDefaultInstance() {
}

AdjacencyLists_Adjacency::AdjacencyLists_Adjacency(const AdjacencyLists_Adjacency& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AdjacencyLists_Adjacency::SharedCtor() {
  _cached_size_ = 0;
  id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AdjacencyLists_Adjacency::~AdjacencyLists_Adjacency() {
  SharedDtor();
}

void AdjacencyLists_Adjacency::SharedDtor() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    delete id_;
  }
  if (this != default_instance_) {
  }
}

void AdjacencyLists_Adjacency::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AdjacencyLists_Adjacency::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AdjacencyLists_Adjacency_descriptor_;
}

const AdjacencyLists_Adjacency& AdjacencyLists_Adjacency::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_adjacency_5flist_2eproto();
  return *default_instance_;
}

AdjacencyLists_Adjacency* AdjacencyLists_Adjacency::default_instance_ = NULL;

AdjacencyLists_Adjacency* AdjacencyLists_Adjacency::New() const {
  return new AdjacencyLists_Adjacency;
}

void AdjacencyLists_Adjacency::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_id()) {
      if (id_ != &::google::protobuf::internal::kEmptyString) {
        id_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AdjacencyLists_Adjacency::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AdjacencyLists_Adjacency::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AdjacencyLists_Adjacency::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AdjacencyLists_Adjacency::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AdjacencyLists_Adjacency::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AdjacencyLists_Adjacency* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AdjacencyLists_Adjacency*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AdjacencyLists_Adjacency::MergeFrom(const AdjacencyLists_Adjacency& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AdjacencyLists_Adjacency::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AdjacencyLists_Adjacency::CopyFrom(const AdjacencyLists_Adjacency& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdjacencyLists_Adjacency::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void AdjacencyLists_Adjacency::Swap(AdjacencyLists_Adjacency* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AdjacencyLists_Adjacency::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AdjacencyLists_Adjacency_descriptor_;
  metadata.reflection = AdjacencyLists_Adjacency_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int AdjacencyLists_Edges::kEdgesFieldNumber;
#endif  // !_MSC_VER

AdjacencyLists_Edges::AdjacencyLists_Edges()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AdjacencyLists_Edges::InitAsDefaultInstance() {
}

AdjacencyLists_Edges::AdjacencyLists_Edges(const AdjacencyLists_Edges& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AdjacencyLists_Edges::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AdjacencyLists_Edges::~AdjacencyLists_Edges() {
  SharedDtor();
}

void AdjacencyLists_Edges::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AdjacencyLists_Edges::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AdjacencyLists_Edges::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AdjacencyLists_Edges_descriptor_;
}

const AdjacencyLists_Edges& AdjacencyLists_Edges::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_adjacency_5flist_2eproto();
  return *default_instance_;
}

AdjacencyLists_Edges* AdjacencyLists_Edges::default_instance_ = NULL;

AdjacencyLists_Edges* AdjacencyLists_Edges::New() const {
  return new AdjacencyLists_Edges;
}

void AdjacencyLists_Edges::Clear() {
  edges_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AdjacencyLists_Edges::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .range.db.AdjacencyLists.Adjacency edges = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_edges:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_edges()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_edges;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AdjacencyLists_Edges::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .range.db.AdjacencyLists.Adjacency edges = 1;
  for (int i = 0; i < this->edges_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->edges(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AdjacencyLists_Edges::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .range.db.AdjacencyLists.Adjacency edges = 1;
  for (int i = 0; i < this->edges_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->edges(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AdjacencyLists_Edges::ByteSize() const {
  int total_size = 0;

  // repeated .range.db.AdjacencyLists.Adjacency edges = 1;
  total_size += 1 * this->edges_size();
  for (int i = 0; i < this->edges_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->edges(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AdjacencyLists_Edges::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AdjacencyLists_Edges* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AdjacencyLists_Edges*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AdjacencyLists_Edges::MergeFrom(const AdjacencyLists_Edges& from) {
  GOOGLE_CHECK_NE(&from, this);
  edges_.MergeFrom(from.edges_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AdjacencyLists_Edges::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AdjacencyLists_Edges::CopyFrom(const AdjacencyLists_Edges& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdjacencyLists_Edges::IsInitialized() const {

  for (int i = 0; i < edges_size(); i++) {
    if (!this->edges(i).IsInitialized()) return false;
  }
  return true;
}

void AdjacencyLists_Edges::Swap(AdjacencyLists_Edges* other) {
  if (other != this) {
    edges_.Swap(&other->edges_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AdjacencyLists_Edges::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AdjacencyLists_Edges_descriptor_;
  metadata.reflection = AdjacencyLists_Edges_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int AdjacencyLists::kForwardEdgesFieldNumber;
const int AdjacencyLists::kReverseEdgesFieldNumber;
#endif  // !_MSC_VER

AdjacencyLists::AdjacencyLists()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AdjacencyLists::InitAsDefaultInstance() {
  forwardedges_ = const_cast< ::range::db::AdjacencyLists_Edges*>(&::range::db::AdjacencyLists_Edges::default_instance());
  reverseedges_ = const_cast< ::range::db::AdjacencyLists_Edges*>(&::range::db::AdjacencyLists_Edges::default_instance());
}

AdjacencyLists::AdjacencyLists(const AdjacencyLists& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AdjacencyLists::SharedCtor() {
  _cached_size_ = 0;
  forwardedges_ = NULL;
  reverseedges_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AdjacencyLists::~AdjacencyLists() {
  SharedDtor();
}

void AdjacencyLists::SharedDtor() {
  if (this != default_instance_) {
    delete forwardedges_;
    delete reverseedges_;
  }
}

void AdjacencyLists::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AdjacencyLists::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AdjacencyLists_descriptor_;
}

const AdjacencyLists& AdjacencyLists::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_adjacency_5flist_2eproto();
  return *default_instance_;
}

AdjacencyLists* AdjacencyLists::default_instance_ = NULL;

AdjacencyLists* AdjacencyLists::New() const {
  return new AdjacencyLists;
}

void AdjacencyLists::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_forwardedges()) {
      if (forwardedges_ != NULL) forwardedges_->::range::db::AdjacencyLists_Edges::Clear();
    }
    if (has_reverseedges()) {
      if (reverseedges_ != NULL) reverseedges_->::range::db::AdjacencyLists_Edges::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AdjacencyLists::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .range.db.AdjacencyLists.Edges forwardEdges = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_forwardedges()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_reverseEdges;
        break;
      }

      // required .range.db.AdjacencyLists.Edges reverseEdges = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_reverseEdges:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_reverseedges()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AdjacencyLists::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .range.db.AdjacencyLists.Edges forwardEdges = 1;
  if (has_forwardedges()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->forwardedges(), output);
  }

  // required .range.db.AdjacencyLists.Edges reverseEdges = 2;
  if (has_reverseedges()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->reverseedges(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AdjacencyLists::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .range.db.AdjacencyLists.Edges forwardEdges = 1;
  if (has_forwardedges()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->forwardedges(), target);
  }

  // required .range.db.AdjacencyLists.Edges reverseEdges = 2;
  if (has_reverseedges()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->reverseedges(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AdjacencyLists::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .range.db.AdjacencyLists.Edges forwardEdges = 1;
    if (has_forwardedges()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->forwardedges());
    }

    // required .range.db.AdjacencyLists.Edges reverseEdges = 2;
    if (has_reverseedges()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->reverseedges());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AdjacencyLists::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AdjacencyLists* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AdjacencyLists*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AdjacencyLists::MergeFrom(const AdjacencyLists& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_forwardedges()) {
      mutable_forwardedges()->::range::db::AdjacencyLists_Edges::MergeFrom(from.forwardedges());
    }
    if (from.has_reverseedges()) {
      mutable_reverseedges()->::range::db::AdjacencyLists_Edges::MergeFrom(from.reverseedges());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AdjacencyLists::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AdjacencyLists::CopyFrom(const AdjacencyLists& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdjacencyLists::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_forwardedges()) {
    if (!this->forwardedges().IsInitialized()) return false;
  }
  if (has_reverseedges()) {
    if (!this->reverseedges().IsInitialized()) return false;
  }
  return true;
}

void AdjacencyLists::Swap(AdjacencyLists* other) {
  if (other != this) {
    std::swap(forwardedges_, other->forwardedges_);
    std::swap(reverseedges_, other->reverseedges_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AdjacencyLists::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AdjacencyLists_descriptor_;
  metadata.reflection = AdjacencyLists_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace range

// @@protoc_insertion_point(global_scope)
